import type { HtmlSourceDefinition } from '../source-definition.js';

export const CURATED_HTML_SOURCES: HtmlSourceDefinition[] = [
  {
    id: 'visit-anaheim-things-to-do',
    name: 'Visit Anaheim Things To Do',
    category: 'Activities',
    url: 'https://www.visitanaheim.org/things-to-do/',
    region: 'Orange County',
    city: 'Anaheim',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'tourism'],
  },
  {
    id: 'discovery-cube-events',
    name: 'Discovery Cube Events',
    category: 'Activities',
    url: 'https://www.discoverycube.org/orange-county/events/',
    region: 'Orange County',
    city: 'Santa Ana',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'stem', 'kids'],
  },
  {
    id: 'visit-anaheim-restaurants',
    name: 'Visit Anaheim Restaurants',
    category: 'Restaurants',
    url: 'https://www.visitanaheim.org/restaurants/',
    region: 'Orange County',
    city: 'Anaheim',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'dining'],
  },
  {
    id: 'discover-la-dining',
    name: 'Discover Los Angeles Dining',
    category: 'Restaurants',
    url: 'https://www.discoverlosangeles.com/food-drink',
    region: 'Los Angeles',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'tourism', 'dining'],
  },
  {
    id: 'oc-parks-trails',
    name: 'OC Parks Trails',
    category: 'Nature',
    url: 'https://ocparks.com/parks-trails',
    region: 'Orange County',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'parks', 'trails'],
  },
  {
    id: 'visit-temecula-outdoors',
    name: 'Visit Temecula Outdoors',
    category: 'Nature',
    url: 'https://www.visittemeculavalley.com/things-to-do/outdoors/',
    region: 'Temecula',
    city: 'Temecula',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'outdoors'],
  },
  {
    id: 'visit-anaheim-events',
    name: 'Visit Anaheim Events',
    category: 'SpecialEvents',
    url: 'https://www.visitanaheim.org/events/',
    region: 'Orange County',
    city: 'Anaheim',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'events'],
  },
  {
    id: 'sandiego-org-events',
    name: 'San Diego Events',
    category: 'SpecialEvents',
    url: 'https://www.sandiego.org/explore/events.aspx',
    region: 'San Diego',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'events'],
  },
];
