import type { HtmlSourceDefinition } from '../source-definition.js';

export const CURATED_HTML_SOURCES: HtmlSourceDefinition[] = [
  {
    id: 'visit-anaheim-things-to-do',
    name: 'Visit Anaheim Things To Do',
    category: 'Activities',
    url: 'https://www.visitanaheim.org/things-to-do/',
    region: 'Orange County',
    city: 'Anaheim',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'tourism'],
    includeUrlPatterns: ['/things-to-do/'],
    excludeUrlPatterns: ['/ana-cam/', '/meetings/', '/travel-trade/', '/partners/', '/media/'],
    excludeTitlePatterns: [
      'featured',
      'skip to main content',
      'things to do',
      'southern california',
      'pristine beaches',
      'world-famous theme park',
      'try something new',
      'epicenter of fun',
      'treat yourself',
      'head to the beach',
    ],
  },
  {
    id: 'discovery-cube-events',
    name: 'Discovery Cube Events',
    category: 'Activities',
    url: 'https://www.discoverycube.org/orange-county/events/',
    region: 'Orange County',
    city: 'Santa Ana',
    itemSelector: '.event-row a',
    maxItems: 20,
    tags: ['official', 'stem', 'kids'],
    excludeTitlePatterns: ['register', 'learn more', 'visit'],
  },
  {
    id: 'visit-anaheim-restaurants',
    name: 'Visit Anaheim Restaurants',
    category: 'Restaurants',
    url: 'https://www.visitanaheim.org/restaurants/',
    region: 'Orange County',
    city: 'Anaheim',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'dining'],
    includeUrlPatterns: ['/restaurants/'],
    excludeUrlPatterns: ['/ana-cam/', '/meetings/', '/travel-trade/', '/partners/', '/media/'],
    excludeTitlePatterns: ['featured', 'restaurants', 'skip to main content'],
  },
  {
    id: 'discover-la-dining',
    name: 'Discover Los Angeles Dining',
    category: 'Restaurants',
    url: 'https://www.discoverlosangeles.com/food-drink',
    region: 'Los Angeles',
    itemSelector: '.views-row .views-field-title a',
    maxItems: 20,
    tags: ['official', 'tourism', 'dining'],
    excludeTitlePatterns: ['things to do in los angeles this weekend'],
  },
  {
    id: 'oc-parks-trails',
    name: 'OC Parks Trails',
    category: 'Nature',
    url: 'https://ocparks.com/parks-trails',
    region: 'Orange County',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'parks', 'trails'],
    allowNavigationLinks: true,
    includeUrlPatterns: ['https://ocparks.com/'],
    excludeUrlPatterns: [
      '/parks/alerts',
      '/contact/connect',
      '/park-rules',
      '/permits',
    ],
    excludeTitlePatterns: ['skip to main content', 'alerts', 'facebook', 'twitter', 'youtube', 'home'],
  },
  {
    id: 'visit-temecula-outdoors',
    name: 'Visit Temecula Outdoors',
    category: 'Nature',
    url: 'https://www.visittemeculavalley.com/things-to-do/outdoors/',
    region: 'Temecula',
    city: 'Temecula',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'outdoors'],
    includeUrlPatterns: ['/things-to-do/outdoors/'],
    excludeTitlePatterns: ['skip to main content', 'book your trip', 'things to do'],
  },
  {
    id: 'visit-anaheim-events',
    name: 'Visit Anaheim Events',
    category: 'SpecialEvents',
    url: 'https://www.visitanaheim.org/events/',
    region: 'Orange County',
    city: 'Anaheim',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'events'],
    includeUrlPatterns: ['/events/'],
    excludeUrlPatterns: ['/ana-cam/', '/meetings/', '/travel-trade/', '/partners/', '/media/'],
    excludeTitlePatterns: ['events', 'event calendar', 'skip to main content'],
  },
  {
    id: 'sandiego-org-events',
    name: 'San Diego Events',
    category: 'SpecialEvents',
    url: 'https://www.sandiego.org/explore/events.aspx',
    region: 'San Diego',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'events'],
    includeUrlPatterns: ['/events-festivals/'],
    excludeTitlePatterns: ['english', 'skip to main content'],
  },
  {
    id: 'opentable-oc-fun-restaurants',
    name: 'OpenTable Orange County Fun Restaurants',
    category: 'Restaurants',
    url: 'https://www.opentable.com/features/fun-restaurants-orange-ca',
    region: 'Orange County',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['discovery', 'restaurants', 'fun', 'ambience', 'reservation-platform'],
    includeUrlPatterns: ['/r/', '/features/', 'opentable.com/features/'],
    excludeUrlPatterns: ['/help/', '/legal/', '/blog/', '/gift-cards/', '/signin'],
    excludeTitlePatterns: ['sign in', 'help', 'legal', 'privacy policy', 'gift cards', 'open app'],
  },
  {
    id: 'opentable-oc-ambience',
    name: "OpenTable Orange County Diners' Choice Ambience",
    category: 'Restaurants',
    url: 'https://www.opentable.com/diners-choice/orange-county/ambience',
    region: 'Orange County',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['discovery', 'restaurants', 'ambience', 'reservation-platform'],
    includeUrlPatterns: ['/r/', '/diners-choice/', 'opentable.com/diners-choice/'],
    excludeUrlPatterns: ['/help/', '/legal/', '/blog/', '/gift-cards/', '/signin'],
    excludeTitlePatterns: ['sign in', 'help', 'legal', 'privacy policy', 'gift cards', 'open app'],
  },
  {
    id: 'opentable-oc-restaurants',
    name: 'OpenTable Orange County Restaurants',
    category: 'Restaurants',
    url: 'https://www.opentable.com/metro/orange-county-restaurants',
    region: 'Orange County',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['discovery', 'restaurants', 'reservation-platform'],
    includeUrlPatterns: ['/r/', '/metro/', 'opentable.com/metro/'],
    excludeUrlPatterns: ['/help/', '/legal/', '/blog/', '/gift-cards/', '/signin'],
    excludeTitlePatterns: ['sign in', 'help', 'legal', 'privacy policy', 'gift cards', 'open app'],
  },
  {
    id: 'eater-la-openings',
    name: 'Eater LA Restaurant Openings',
    category: 'Restaurants',
    url: 'https://la.eater.com/restaurant-openings',
    region: 'Los Angeles',
    city: 'Los Angeles',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['discovery', 'restaurants', 'openings', 'editorial'],
    includeUrlPatterns: ['la.eater.com/', '/restaurant-openings/', '/maps/'],
    excludeUrlPatterns: ['/about', '/contact', '/newsletters', '/auth/'],
    excludeTitlePatterns: ['subscribe', 'newsletter', 'contact', 'privacy policy', 'terms'],
  },
  {
    id: 'eater-san-diego-openings',
    name: 'Eater San Diego Restaurant Openings',
    category: 'Restaurants',
    url: 'https://sandiego.eater.com/openings',
    region: 'San Diego',
    city: 'San Diego',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['discovery', 'restaurants', 'openings', 'editorial'],
    includeUrlPatterns: ['sandiego.eater.com/', '/openings', '/maps/'],
    excludeUrlPatterns: ['/about', '/contact', '/newsletters', '/auth/'],
    excludeTitlePatterns: ['subscribe', 'newsletter', 'contact', 'privacy policy', 'terms'],
  },
  {
    id: 'fever-la-food-drink',
    name: 'Fever Los Angeles Food & Drink',
    category: 'SpecialEvents',
    url: 'https://feverup.com/en/los-angeles/food',
    region: 'Los Angeles',
    city: 'Los Angeles',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['discovery', 'food-drink', 'immersive', 'ticketing', 'pop-up'],
    includeUrlPatterns: ['/en/los-angeles/', '/m/', '/food', '/drinks-afterwork', '/restaurants', '/tasting'],
    excludeUrlPatterns: ['/login', '/signup', '/gift', '/cart', '/organizers'],
    excludeTitlePatterns: ['login', 'sign up', 'gift card', 'help', 'download app'],
  },
  {
    id: 'fever-la-drinks-happy-hour',
    name: 'Fever Los Angeles Drinks & Happy Hour',
    category: 'SpecialEvents',
    url: 'https://feverup.com/en/los-angeles/drinks-afterwork',
    region: 'Los Angeles',
    city: 'Los Angeles',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['discovery', 'bars', 'cocktails', 'immersive', 'ticketing', 'pop-up'],
    includeUrlPatterns: ['/en/los-angeles/', '/m/', '/drinks-afterwork', '/food'],
    excludeUrlPatterns: ['/login', '/signup', '/gift', '/cart', '/organizers'],
    excludeTitlePatterns: ['login', 'sign up', 'gift card', 'help', 'download app'],
  },
  {
    id: 'bucketlisters-food-drinks',
    name: 'Bucket Listers Food & Drinks',
    category: 'SpecialEvents',
    url: 'https://bucketlisters.com/explore/collection/61',
    region: 'Los Angeles',
    city: 'Los Angeles',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['discovery', 'food-drink', 'ticketing', 'pop-up', 'experiences'],
    includeUrlPatterns: ['bucketlisters.com', '/explore/', '/experiences/', '/things-to-do/'],
    excludeUrlPatterns: ['/login', '/signup', '/gift-cards', '/about', '/careers'],
    excludeTitlePatterns: ['sign in', 'sign up', 'gift cards', 'careers', 'about us'],
  },
  {
    id: 'discover-la-eat-drink',
    name: 'Discover Los Angeles Eat & Drink',
    category: 'Restaurants',
    url: 'https://www.discoverlosangeles.com/eat-drink',
    region: 'Los Angeles',
    city: 'Los Angeles',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'tourism', 'restaurants', 'discovery'],
    includeUrlPatterns: ['/eat-drink', '/food-drink', '/dinela', '/whats-new-in-los-angeles'],
    excludeUrlPatterns: ['/travel-trade/', '/industry/', '/partners/', '/about-us/'],
    excludeTitlePatterns: ['sign up', 'newsletter', 'privacy policy', 'advertise', 'accessibility'],
  },
  {
    id: 'secret-la-food-drink',
    name: 'Secret Los Angeles Food & Drink',
    category: 'SpecialEvents',
    url: 'https://secretlosangeles.com/food-drink/page/101/',
    region: 'Los Angeles',
    city: 'Los Angeles',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['editorial', 'discovery', 'food-drink', 'pop-up', 'bars'],
    includeUrlPatterns: ['secretlosangeles.com/', '/food-drink/', '/themed-restaurants', '/pop-up'],
    excludeUrlPatterns: ['/advertise', '/about', '/privacy-policy', '/contact'],
    excludeTitlePatterns: ['advertise', 'privacy policy', 'contact', 'about us'],
  },
  {
    id: 'san-diego-mag-food-drink',
    name: 'San Diego Magazine Food & Drink',
    category: 'Restaurants',
    url: 'https://sandiegomagazine.com/category/food-drink/',
    region: 'San Diego',
    city: 'San Diego',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['editorial', 'discovery', 'restaurants', 'bars', 'openings'],
    includeUrlPatterns: ['sandiegomagazine.com/', '/food-drink/', '/community-event/'],
    excludeUrlPatterns: ['/subscribe', '/advertise', '/about-us', '/contact-us'],
    excludeTitlePatterns: ['subscribe', 'advertise', 'contact us', 'about us'],
  },
  {
    id: 'orange-coast-hidden-oc-eat-drink',
    name: 'Orange Coast Hidden O.C. Eat & Drink',
    category: 'Restaurants',
    url: 'https://orangecoast.com/feature/hidden-o-c-eat-drink/',
    region: 'Orange County',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['editorial', 'discovery', 'restaurants', 'hidden-gems', 'bars'],
    includeUrlPatterns: ['orangecoast.com/', '/feature/', '/o-c-guides/', '/ocdining/'],
    excludeUrlPatterns: ['/subscribe', '/advertise', '/contact', '/privacy-policy'],
    excludeTitlePatterns: ['subscribe', 'advertise', 'contact', 'privacy policy'],
  },
  {
    id: 'visit-temecula-restaurants',
    name: 'Visit Temecula Valley Restaurants',
    category: 'Restaurants',
    url: 'https://www.visittemeculavalley.com/restaurants/',
    region: 'Temecula',
    city: 'Temecula',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'tourism', 'restaurants', 'discovery'],
    includeUrlPatterns: ['/restaurants/', '/things-to-do/old-town/dining/', '/restaurants/dining-options/'],
    excludeUrlPatterns: ['/meetings/', '/partners/', '/media/', '/weddings/'],
    excludeTitlePatterns: ['skip to main content', 'book your trip', 'privacy policy', 'request guide'],
  },
  {
    id: 'discover-la-whats-new-dining',
    name: "Discover Los Angeles What's New Dining",
    category: 'Restaurants',
    url: 'https://www.discoverlosangeles.com/whats-new-in-los-angeles-springsummer-2025',
    region: 'Los Angeles',
    city: 'Los Angeles',
    itemSelector: 'a',
    maxItems: 20,
    tags: ['official', 'tourism', 'restaurants', 'openings', 'discovery'],
    includeUrlPatterns: ['/whats-new-in-los-angeles', '/eat-drink', '/food-drink'],
    excludeUrlPatterns: ['/travel-trade/', '/industry/', '/partners/', '/about-us/'],
    excludeTitlePatterns: ['sign up', 'newsletter', 'privacy policy', 'advertise', 'accessibility'],
  },
];
